In [1]:
import pandas as pd

In [26]:
league = "nwsl"
season = 2026

In [55]:
# Read the rosters at the end of last season
old = pd.read_csv(league + "/" + str(season - 1) + "_end.csv")
old

    team             player
0     LA  Angelina Anderson
1     LA     Hannah Seabert
2     LA      Sara Doorsoun
3     LA       Sarah Gorden
4     LA          Savy King
..   ...                ...
395  UTA         Aria Nagai
396  UTA         Abby Boyan
397  UTA      Dana Foederer
398  UTA         Emily Gray
399  UTA  Bianca St-Georges

[400 rows x 2 columns]

In [56]:
# Read the rosters at the beginning of this season
new = pd.read_csv(league + "/" + str(season) + "_start.csv")
new

    team             player
0     LA  Angelina Anderson
1     LA       Faith Nguyen
2     LA    Hannnah Seabert
3     LA      Karsyn Cherry
4     LA       Sarah Gorden
..   ...                ...
420  DEN            Melissa
421  DEN            Kössler
422  DEN       Janine Sonis
423  DEN      Olivia Thomas
424  DEN          Meg Boade

[425 rows x 2 columns]

In [57]:
# Join the rosters
df = (
    old.set_index("player")
    .join(new.set_index("player"), how="outer", lsuffix="_old", rsuffix="_new")
    .reset_index()
)
df

              player team_old team_new
0          AD Franch      KCC      NaN
1     Aaliyah Farmer      NaN      CHI
2         Abby Boyan      UTA      NaN
3    Abby Dahlkemper      BAY      BAY
4         Abby Smith      HOU      DEN
..               ...      ...      ...
512     Yazmeen Ryan      HOU      HOU
513   Yuna McCormack      NaN      DEN
514    Zara Chavoshi      ORL      ORL
515     Zoe Matthews      HOU      NaN
516    Élisabeth Tsé      NaN      WAS

[517 rows x 3 columns]

In [58]:
# Find all the duplicate entries
pd.concat(g for _, g in df.groupby("player") if len(g) > 1)

ValueError: No objects to concatenate

In [59]:
# Check that all newly signed players are correct
signed = df[df["team_old"].isna()].sort_values("player")
signed.to_csv(league + "/signed.csv", index=False)
signed

               player team_old team_new
1      Aaliyah Farmer      NaN      CHI
9           Alba Caño      NaN      BOS
10     Aldana Cometti      NaN      BAY
11     Aleigh Gambone      NaN      BOS
27   Amanda Gutierres      NaN      BOS
..                ...      ...      ...
496         Teagan Wy      NaN      GFC
499   Tessa Dellarose      NaN      CHI
506     Uno Shiragaki      NaN       NC
513    Yuna McCormack      NaN      DEN
516     Élisabeth Tsé      NaN      WAS

[117 rows x 3 columns]

In [60]:
# Check that all dropped players are correct
dropped = df[df["team_new"].isna()].sort_values("player")
dropped.to_csv(league + "/dropped.csv", index=False)
dropped

               player team_old team_new
0           AD Franch      KCC      NaN
2          Abby Boyan      UTA      NaN
7     Aisha Solórzano      UTA      NaN
15          Ali Riley       LA      NaN
16        Aline Gomes       NC      NaN
..                ...      ...      ...
504       Tyler Lussi       NC      NaN
505      Uchenna Kanu      LOU      NaN
509   Veronica Latsko      RGN      NaN
510  Victoria Pickett       NC      NaN
515      Zoe Matthews      HOU      NaN

[92 rows x 3 columns]

In [61]:
# Write output to file
df.to_csv(
    league + "/" + str(season - 1) + "_" + str(season) + "_movement.csv", index=False
)