In [1]:
import pandas as pd
from icalendar import Calendar, Event
from zoneinfo import ZoneInfo
from common import NWSL

In [23]:
df = pd.DataFrame([], columns=["date", "time", "home", "away"])
df

Empty DataFrame
Columns: [date, time, home, away]
Index: []

In [24]:
et = ZoneInfo("America/New_York")
ct = ZoneInfo("America/Chicago")
mt = ZoneInfo("America/Denver")
pt = ZoneInfo("America/Los_Angeles")

tzs = {
    "GFC": et,
    "POR": pt,
    "LA": pt,
    "CHI": ct,
    "WAS": et,
    "SD": pt,
    "NC": et,
    "RGN": pt,
    "LOU": et,
    "HOU": ct,
    "ORL": et,
    "KCC": ct,
    "UTA": mt,
    "BAY": pt,
    "DEN": mt,
    "BOS": et,
}

In [25]:
f = open('data/NWSL.ics','rb')
cal = Calendar.from_ical(f.read())
for component in cal.walk():
    if component.name == "VEVENT":
        try:
            summary = component.get('summary')[3:]
            home = NWSL.map_team(summary.split(" vs ")[0])
            away = NWSL.map_team(summary.split(" vs ")[1])
            date = component.get('dtstart').dt.astimezone(tzs[home])
            df.loc[len(df)] =[date.date(), date.time().strftime("%-I:%M %p"),home, away]
        except:
            print('pass')
f.close()

df

pass

           date      time home away
0    2026-03-13   8:00 PM  WAS  POR
1    2026-03-14  12:30 PM  BOS  GFC
2    2026-03-14   3:00 PM  KCC  UTA
3    2026-03-14   3:30 PM  BAY  DEN
4    2026-03-14   7:00 PM   NC  LOU
..          ...       ...  ...  ...
179  2026-09-06   1:00 PM  POR  WAS
180  2026-09-06   7:00 PM  ORL  HOU
181  2026-09-06   6:00 PM  RGN   SD
182  2026-09-11   6:30 PM  LOU  GFC
183  2026-09-11   7:00 PM  KCC  ORL

[184 rows x 4 columns]

In [26]:
decision_day = pd.DataFrame(
    [
        ["2026-11-01", "", "LA", "BOS"],
        ["2026-11-01", "", "BAY", "SD"],
        ["2026-11-01", "", "GFC", "UTA"],
        ["2026-11-01", "", "HOU", "POR"],
        ["2026-11-01", "", "NC", "DEN"],
        ["2026-11-01", "", "LOU", "KCC"],
        ["2026-11-01", "", "RGN", "ORL"],
        ["2026-11-01", "", "WAS", "CHI"],
    ],
    columns=["date", "time", "home", "away"],
)

df = pd.concat([df, decision_day])

In [27]:
df

          date      time home away
0   2026-03-13   8:00 PM  WAS  POR
1   2026-03-14  12:30 PM  BOS  GFC
2   2026-03-14   3:00 PM  KCC  UTA
3   2026-03-14   3:30 PM  BAY  DEN
4   2026-03-14   7:00 PM   NC  LOU
..         ...       ...  ...  ...
3   2026-11-01            HOU  POR
4   2026-11-01             NC  DEN
5   2026-11-01            LOU  KCC
6   2026-11-01            RGN  ORL
7   2026-11-01            WAS  CHI

[192 rows x 4 columns]

In [28]:
df.to_csv("data/2026_schedule.csv", index=False)